name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Algorithm1
      id: algorithm1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Algorithm1
        setup-command: ''
        command: mvn test -Dtest=Algorithm1Test
        timeout: 20
    - name: Algorithm2
      id: algorithm2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Algorithm2
        setup-command: ''
        command: mvn test -Dtest=Algorithm2Test
        timeout: 20
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ALGORITHM1_RESULTS: "${{steps.algorithm1.outputs.result}}"
        ALGORITHM2_RESULTS: "${{steps.algorithm2.outputs.result}}"
      with:
        runners: algorithm1,algorithm2